### ISSUE TITLE
Allow installing federation in cluster scope

### ISSUE THREAD

**Issue by csrwng** [openshift/federation-v2-operator#29]
We are planning on using this operator to deploy Federation along with Hive in production. This use case requires federation controllers to run in cluster scope instead of namespace scope.

**Comment by csrwng** [comment]
@pmorie

**Comment by pmorie** [comment]
I think this is definitely reasonable, we have talked about having different CSVs for ns- and cluster- scope deployments, but I'm not sure we know the right patterns here yet.
