### ISSUE TITLE
catalogsource is not created with current operator version

### ISSUE THREAD

**Issue by erinaboyd** [openshift/federation-v2-operator#55]
[root@ip-10-0-17-210 federation-v2-operator]# ./scripts/install-using-catalog-source.sh pmorie
catalogsource "federation" created
operatorgroup "namespaced-federation" created
subscription "namespaced-federation-sub" created

Result:
NAME                                             READY     STATUS    RESTARTS   AGE       IP            NODE
federation-controller-manager-5fb55c99bb-4t7zz   1/1       Running   0          6m        10.131.0.31   ip-10-10-132-211.ec2.internal
[root@ip-10-0-17-210 federation-v2-operator]# oc get catalogsource
No resources found.
[root@ip-10-0-17-210 federation-v2-operator]# oc get subscription
NAME                        AGE
namespaced-federation-sub   10m
[root@ip-10-0-17-210 federation-v2-operator]# oc get catalogsource
No resources found.
[root@ip-10-0-17-210 federation-v2-operator]# oc get operatorgroup
NAME                    AGE
namespaced-federation   10m
[root@ip-10-0-17-210 federation-v2-operator]#

**Comment by pmorie** [comment]
The catalog source is created in the `openshift-operator-lifecycle-manager` ns, would you check to see if it was created there?

**Comment by erinaboyd** [comment]
It was.
